<?php

namespace Database\Seeders;

use App\Models\Bank;
use Illuminate\Database\Seeder;

class BanksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $banks = [
            "AB Bank Ltd.",
            "Airtel Payments Bank Limited",
            "American Express Banking Corporation",
            "Andhra Pradesh Grameena Vikas Bank",
            "Andhra Pragathi Grameena Bank",
            "Arunachal Pradesh Rural Bank",
            "Aryavart Bank",
            "Assam Gramin Vikash Bank",
            "Au Small Finance Bank Limited",
            "Australia and New Zealand Banking Group Ltd.",
            "Axis Bank Ltd.",
            "Bandhan Bank Ltd",
            "Bangiya Gramin Vikas Bank",
            "Bank of America",
            "Bank of Bahrain & Kuwait BSC",
            "Bank of Baroda",
            "Bank of Ceylon",
            "Bank of China",
            "Bank of India",
            "Bank of Maharashtra",
            "Bank of Nova Scotia",
            "Barclays Bank Plc.",
            "Baroda Gujarat Gramin Bank",
            "Baroda Rajasthan Kshetriya Gramin Bank",
            "Baroda UP Bank",
            "BNP Paribas",
            "Canara Bank",
            "Capital Small Finance Bank Limited",
            "Central Bank of India",
            "Chaitanya Godavari Grameena Bank",
            "Chhattisgarh Rajya Gramin Bank",
            "Citibank N.A.",
            "City Union Bank Ltd",
            "Cooperatieve Rabobank U.A",
            "Credit Agricole Corporate & Investment Bank",
            "Credit Suisse A.G",
            "CSB Bank Ltd",
            "CTBC Bank Co., Ltd.",
            "Dakshin Bihar Gramin Bank",
            "DBS Bank India Limited*",
            "DCB Bank Ltd.",
            "Deutsche Bank",
            "Dhanlaxmi Bank Ltd.",
            "Doha Bank Q.P.S.C",
            "Ellaquai Dehati Bank",
            "Emirates Bank NBD",
            "Equitas Small Finance Bank Limited",
            "ESAF Small Finance Bank Limited",
            "Federal Bank Ltd.",
            "Fincare Small Finance Bank Limited",
            "Fino Payments Bank Limited",
            "First Abu Dhabi Bank PJSC",
            "FirstRand Bank Ltd",
            "HDFC Bank Ltd",
            "Himachal Pradesh Gramin Bank",
            "HSBC Ltd",
            "ICICI Bank Ltd.",
            "IDBI Bank Ltd",
            "IDFC First Bank Ltd",
            "India Post Payments Bank Limited",
            "Indian Bank",
            "Indian Overseas Bank",
            "Induslnd Bank Ltd",
            "Industrial & Commercial Bank of China Ltd",
            "Industrial Bank of Korea",
            "J.P. Morgan Chase Bank N.A",
            "J&K Grameen Bank",
            "Jammu & Kashmir Bank Ltd",
            "Jana Small Finance Bank Limited",
            "Jharkhand Rajya Gramin Bank",
            "JSC VTB Bank",
            "Karnataka Bank Ltd",
            "Karnataka Gramin Bank",
            "Karnataka Vikas Grameena Bank",
            "Karur Vysya Bank Ltd",
            "KEB Hana Bank",
            "Kerala Gramin Bank",
            "Kookmin Bank",
            "Kotak Mahindra Bank Ltd",
            "Krung Thai Bank Public Co. Ltd.",
            "Madhya Pradesh Gramin Bank",
            "Madhyanchal Gramin Bank",
            "Maharashtra Gramin Bank",
            "Manipur Rural Bank",
            "Mashreq Bank PSC",
            "Meghalaya Rural Bank",
            "Mizoram Rural Bank",
            "Mizuho Bank Ltd.",
            "MUFG Bank, Ltd",
            "Nagaland Rural Bank",
            "Nainital Bank Ltd",
            "NatWest Markets Plc",
            "North East Small Finance Bank Limited",
            "Odisha Gramya Bank",
            "Paschim Banga Gramin Bank",
            "Paytm Payments Bank Limited",
            "Prathama UP Gramin Bank",
            "PT Bank Maybank Indonesia TBK",
            "Puduvai Bharathiar Grama Bank",
            "Punjab & Sind Bank",
            "Punjab Gramin Bank",
            "Punjab National Bank",
            "Qatar National Bank (Q.P.S.C.)",
            "Rajasthan Marudhara Gramin Bank",
            "RBL Bank Ltd",
            "Saptagiri Grameena Bank",
            "Sarva Haryana Gramin Bank",
            "Saurashtra Gramin Bank",
            "Sberbank",
            "SBM Bank (India) Limited*",
            "Shinhan Bank",
            "Shivalik Small Finance Bank Limited",
            "Societe Generale",
            "Sonali Bank Ltd.",
            "South Indian Bank Ltd",
            "Standard Chartered Bank",
            "State Bank of India",
            "Sumitomo Mitsui Banking Corporation",
            "Suryoday Small Finance Bank Limited",
            "Tamil Nadu Grama Bank",
            "Tamilnad Mercantile Bank Ltd",
            "Telangana Grameena Bank",
            "Tripura Gramin Bank",
            "UCO Bank",
            "Ujjivan Small Finance Bank Limited",
            "Union Bank of India",
            "United Overseas Bank Ltd",
            "Unity Small Finance Bank Limited",
            "Utkal Grameen bank",
            "Utkarsh Small Finance Bank Limited",
            "Uttar Bihar Gramin Bank",
            "Uttarakhand Gramin Bank",
            "Uttarbanga Kshetriya Gramin Bank",
            "Vidharbha Konkan Gramin Bank",
            "Woori Bank",
            "YES Bank Ltd",
        ];

        foreach ($banks as $bank) {
            Bank::create([
                'name' => $bank,
            ]);
        }
    }
}
